version: "3"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    restart: always

  content-service:
    build: ./content-service
    ports:
      - "5001:5001"
    restart: always
