apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
        - name: content
          image: thahirshaik17/content-service
          ports:
            - containerPort: 5001
